### ISSUE TITLE
Conceptual design for Vector

### ISSUE THREAD

**Issue by altavir** [altavir/kmath#8]
Interfaces and maybe some documentation for Vector

**Comment by altavir** [comment]
[Example implementation without commons-math](https://bitbucket.org/mipt-npm/birefringence/src/default/biref-base/src/main/kotlin/ru/mipt/physics/biref/Vector.kt)
[Example with Commons-math wrapping](https://bitbucket.org/Altavir/dataforge/src/default/dataforge-maths/src/main/kotlin/hep/dataforge/maths/extensions/MathExtensions.kt)

**Comment by Wasabi375** [comment]
I think wrapping around RealMatrix and RealVector is the easier solution. The problem I have with wrapping is that we would also need to wrap around FieldElement and Field if we want to support matrices/vectors using complex numbers, etc. 
If we start to wrap around commons-math we are pretty constrained to the layout they use. On the other hand do we get a lot of implementation that way. I think the question is whether or not we want this to based on commons-math or just be similar to it. Another think to consider is porting this to kotlin-js or native. I guess for that it would be better if we did not follow commons math to closely but I personally don't have the experience with either.

**Comment by altavir** [comment]
The problem with linear algebra is that one wants it to be fast. Commons math is not as fast as standard native algorithms as BLAS or LAPACK, but it is close. 
I think that we should start with some interfaces without thinking about specific implementation and then add one or multiple back-ends.

Using RealVector with complex is out of the question, we need our own interface for that. Maybe take my `NDArray` as a reference. We will need to think ahead and avoid autoboxing for array values to avoid performance losses in future.

**Comment by altavir** [comment]
Closing it for now. Current design for Buffers/Points/Vectors seems to be satisfactory. Need documentation though.
